In [2]:
# SQL Library and Pandas
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect("data.sqlite")

In [3]:
pd.read_sql("""SELECT * FROM employees""", conn)

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102,Sales Rep

In [8]:
pd.read_sql("""
SELECT employeeNumber, lastName
FROM employees;
""", conn).head(10)

  employeeNumber   lastName
0           1002     Murphy
1           1056  Patterson
2           1076   Firrelli
3           1088  Patterson
4           1102     Bondur
5           1143        Bow
6           1165   Jennings
7           1166   Thompson
8           1188   Firrelli
9           1216  Patterson

In [9]:
pd.read_sql("""
SELECT lastName, employeeNumber
FROM employees;
""", conn).head(10)

    lastName employeeNumber
0     Murphy           1002
1  Patterson           1056
2   Firrelli           1076
3  Patterson           1088
4     Bondur           1102
5        Bow           1143
6   Jennings           1165
7   Thompson           1166
8   Firrelli           1188
9  Patterson           1216

In [10]:
pd.read_sql("""
SELECT lastName, employeeNumber AS ID
FROM employees;
""", conn).head(10)

    lastName    ID
0     Murphy  1002
1  Patterson  1056
2   Firrelli  1076
3  Patterson  1088
4     Bondur  1102
5        Bow  1143
6   Jennings  1165
7   Thompson  1166
8   Firrelli  1188
9  Patterson  1216

In [11]:
pd.read_sql("""
SELECT *,
    CASE
        WHEN jobTitle = 'President'
          OR jobTitle = 'VP Sales'
          OR jobTitle = 'VP Marketing'
        THEN 'Executive'
        ELSE 'Not Executive'
    END AS role
FROM employees;
""", conn)

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,role
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,,President,Executive
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002,VP Sales,Executive
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002,VP Marketing,Executive
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056,Sales Manager (APAC),Not Executive
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056,Sale Manager (EMEA),Not Executive
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056,Sales Manager (NA),Not Executive
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep,Not Executive
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep,Not Executive
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep,Not Executive
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep,Not Executive
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep,Not Executive
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep,Not Executive
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep,Not Executive
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep,Not Executive
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102,Sales Rep,Not Executive
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep,Not Executive
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102,Sales Rep,Not Executive
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088,Sales Rep,Not Executive
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088,Sales Rep,Not Executive
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088,Sales Rep,Not Executive
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056,Sales Rep,Not Executive
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621,Sales Rep,Not Executive
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102,Sales Rep,Not Executive

In [12]:
pd.read_sql("""
SELECT LENGTH(lastName) AS name_length
FROM employees;
""", conn)

    name_length
0             6
1             9
2             8
3             9
4             6
5             3
6             8
7             8
8             8
9             9
10            5
11            6
12            6
13            9
14            8
15            4
16            5
17            6
18            5
19            4
20            5
21            4
22            6

In [13]:
pd.read_sql("""
SELECT SUBSTR(jobTitle, 1, 2) AS short_title
FROM employees;
""", conn)

   short_title
0           Pr
1           VP
2           VP
3           Sa
4           Sa
5           Sa
6           Sa
7           Sa
8           Sa
9           Sa
10          Sa
11          Sa
12          Sa
13          Sa
14          Sa
15          Sa
16          Sa
17          Sa
18          Sa
19          Sa
20          Sa
21          Sa
22          Sa

In [16]:
pd.read_sql("""
SELECT ROUND(priceEach * quantityOrdered) AS total_price
FROM orderDetails;
""", conn)

      total_price
0          4080.0
1          2755.0
2          1660.0
3          1729.0
4          2702.0
...           ...
2991       6262.0
2992        986.0
2993       3435.0
2994        554.0
2995       1709.0

[2996 rows x 1 columns]

In [18]:
pd.read_sql("""
SELECT ROUND(priceEach * quantityOrdered) AS total_price
FROM orderdetails;
""", conn).sum()

total_price    9604251.0
dtype: float64

In [19]:
pd.read_sql("""
SELECT
    orderDate,
    STRFTIME('%d', orderDate) AS day,
    STRFTIME('%m', orderDate) AS month,
    STRFTIME('%Y', orderDate) AS year
FROM orders;
""", conn)

      orderDate day month  year
0    2003-01-06  06    01  2003
1    2003-01-09  09    01  2003
2    2003-01-10  10    01  2003
3    2003-01-29  29    01  2003
4    2003-01-31  31    01  2003
..          ...  ..   ...   ...
321  2005-05-29  29    05  2005
322  2005-05-30  30    05  2005
323  2005-05-30  30    05  2005
324  2005-05-31  31    05  2005
325  2005-05-31  31    05  2005

[326 rows x 4 columns]

In [20]:
conn.close()